---
- name: Install GamestonkTerminal Jupyter Docker Container
  hosts: all
  become: true
  vars:
    - ansible_python_interpreter: auto_silent

  tasks:
    - name: Include a Docker playbook
      include_role:
        name: docker
        tasks_from: docker.yml

    - name: Start a GST Jupyter container
      docker_container:
        name: gst-jupyter
        image: ghcr.io/gamestonkterminal/gst-poetry-jupyter:latest
        state: started
        ports:
          - "8888:8888"
      vars:
        ansible_python_interpreter: /bin/python3.8
