---
- name: Update a VM and install Docker
  hosts: all
  become: true
  vars:
    - ansible_python_interpreter: auto_silent

  tasks:
    - name: Update yum packages except kernel
      ansible.builtin.yum:
        name: '*'
        exclude: kernel*
        state: latest   # noqa package-latest

    - name: Include a Docker playbook
      ansible.builtin.include_role:
        name: docker
        tasks_from: docker.yml

    - name: Check if Ansible is installed with Python3
      ansible.builtin.shell:
        ansible --version | grep "python version" | grep 3.8   # noqa risky-shell-pipe command-instead-of-shell
      args:
        warn: false
      register: ansible_python3_installed
      changed_when: ansible_python3_installed.stdout == ""
      failed_when: false

    - name: Install Python3 Ansible
      ansible.builtin.pip:
        name: "ansible"
        executable: pip3.8
      when: ansible_python3_installed.stdout | length == 0

    - name: Disable amazon-linux-extras ansible
      ansible.builtin.shell:
        "amazon-linux-extras disable ansible2"   # noqa command-instead-of-shell
      when: ansible_python3_installed.stdout | length == 0

    - name: Add /usr/local/bin to secure_path in /etc/sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults    secure_path ='
        line: Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/local/bin:/usr/bin

    - name: Clean yum cache    # noqa no-changed-when
      ansible.builtin.shell:
        yum clean all    # noqa command-instead-of-shell
      args:
        warn: false

    - name: Remove yum cache    # noqa no-changed-when
      ansible.builtin.shell:
        rm -Rf /var/cache/yum    # noqa command-instead-of-shell
      args:
        warn: false

    - name: Uninstall amazon-linux-extras ansible
      ansible.builtin.yum:
        name: ansible
        state: absent
      when: ansible_python3_installed.stdout | length == 0
