---
- name: Install and configure a Docker server
  hosts: all
  become: true
  vars:
    - ansible_python_interpreter: auto_silent

  tasks:
    - name: Include a Docker playbook
      ansible.builtin.include_role:
        name: docker
        tasks_from: docker.yml
