---
- name: Install and configure a Docker server
  hosts: all
  become: true
  vars:
    - ansible_python_interpreter: auto_silent

  tasks:
    - name: Include a Docker playbook
      ansible.builtin.include_role:
        name: docker
        tasks_from: docker.yml

    - name: List running Docker containers
      ansible.builtin.include_role:
        name: docker
        tasks_from: list_containers.yml
    - ansible.builtin.debug: var=docker_output.stdout_lines   # noqa name[missing] no-free-form
