---
- name: Install and configure a Nginx server
  hosts: all
  become: true
  vars:
    - ansible_python_interpreter: auto_silent

  tasks:
    - name: Include a Nginx playbook
      ansible.builtin.include_role:
        name: nginx
        tasks_from: nginx.yml
