---
- name: Install docker
  ansible.builtin.yum:
    name: docker
    state: present

- name: Start Docker
  ansible.builtin.service:
    name: docker
    enabled: yes    # yamllint disable-line
    state: started
  when: lookup("env", "ansible_skip_service") != "true"

- name: Add vagrant user to group docker
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: true

- name: Check if Python3 is installed
  ansible.builtin.shell:
    rpm -qi python38 | grep -v "not installed"   # noqa risky-shell-pipe command-instead-of-shell
  args:
    warn: false
  register: python38_installed
  changed_when: python38_installed.stdout == ""
  failed_when: false

- name: Enable amazon-linux-extras packages
  ansible.builtin.shell:
    "amazon-linux-extras enable python3.8"   # noqa command-instead-of-shell
  when: python38_installed.stdout|length == 0

- name: Install Python3
  ansible.builtin.yum:
    name: python38
    state: latest   # noqa package-latest
  vars:
    ansible_python_interpreter: /bin/python2.7
  when: python38_installed.stdout|length == 0

- name: Install Python3 Docker
  ansible.builtin.pip:
    name: "docker"
    executable: pip3.8
